"""initial schema

Revision ID: 86e5b3738ff0
Revises: 
Create Date: 2026-03-02 20:06:00.135120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86e5b3738ff0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Text(), nullable=False),
    sa.Column('input_count', sa.Integer(), nullable=True),
    sa.Column('analysis_summary', sa.Text(), nullable=True),
    sa.Column('opportunities', sa.Text(), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_analysis_date', 'analysis_results', ['date'], unique=False)
    op.create_table('block_daily',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('block_code', sa.String(length=20), nullable=False, comment='板块代码'),
    sa.Column('block_name', sa.String(length=50), nullable=False, comment='板块名称'),
    sa.Column('block_type', sa.String(length=20), nullable=True, comment='类型 (industry/concept/area)'),
    sa.Column('trade_date', sa.String(length=8), nullable=False, comment='交易日期'),
    sa.Column('open', sa.Numeric(precision=12, scale=2), nullable=True, comment='开盘'),
    sa.Column('high', sa.Numeric(precision=12, scale=2), nullable=True, comment='最高'),
    sa.Column('low', sa.Numeric(precision=12, scale=2), nullable=True, comment='最低'),
    sa.Column('close', sa.Numeric(precision=12, scale=2), nullable=True, comment='收盘'),
    sa.Column('pct_chg', sa.Numeric(precision=8, scale=4), nullable=True, comment='涨跌幅 (%)'),
    sa.Column('vol', sa.BigInteger(), nullable=True, comment='成交量'),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True, comment='成交额'),
    sa.Column('turnover_rate', sa.Numeric(precision=8, scale=4), nullable=True, comment='换手率'),
    sa.Column('lead_stock', sa.String(length=12), nullable=True, comment='领涨股票代码'),
    sa.Column('up_count', sa.Integer(), nullable=True, comment='上涨个股数'),
    sa.Column('down_count', sa.Integer(), nullable=True, comment='下跌个股数'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('block_code', 'trade_date', name='uq_block_daily'),
    comment='板块日线行情表'
    )
    op.create_index(op.f('ix_block_daily_block_code'), 'block_daily', ['block_code'], unique=False)
    op.create_index(op.f('ix_block_daily_block_type'), 'block_daily', ['block_type'], unique=False)
    op.create_index(op.f('ix_block_daily_trade_date'), 'block_daily', ['trade_date'], unique=False)
    op.create_index('ix_block_daily_type_date', 'block_daily', ['block_type', 'trade_date'], unique=False)
    op.create_table('dragon_tiger',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('trade_date', sa.String(length=8), nullable=False, comment='交易日期'),
    sa.Column('name', sa.String(length=50), nullable=True, comment='股票名称'),
    sa.Column('close', sa.Numeric(precision=12, scale=2), nullable=True, comment='收盘价'),
    sa.Column('pct_chg', sa.Numeric(precision=8, scale=4), nullable=True, comment='涨跌幅 (%)'),
    sa.Column('turnover_rate', sa.Numeric(precision=8, scale=4), nullable=True, comment='换手率 (%)'),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True, comment='总成交额 (万元)'),
    sa.Column('l_buy', sa.Numeric(precision=18, scale=2), nullable=True, comment='买入额 (万元)'),
    sa.Column('l_sell', sa.Numeric(precision=18, scale=2), nullable=True, comment='卖出额 (万元)'),
    sa.Column('net_amount', sa.Numeric(precision=18, scale=2), nullable=True, comment='净买入额 (万元)'),
    sa.Column('net_rate', sa.Numeric(precision=8, scale=4), nullable=True, comment='净买入占比 (%)'),
    sa.Column('reason', sa.String(length=200), nullable=True, comment='上榜原因'),
    sa.Column('inst_buy', sa.Numeric(precision=18, scale=2), nullable=True, comment='机构买入 (万元)'),
    sa.Column('inst_sell', sa.Numeric(precision=18, scale=2), nullable=True, comment='机构卖出 (万元)'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('ts_code', sa.String(length=12), nullable=False, comment='股票代码 (000001.SZ)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ts_code', 'trade_date', name='uq_dragon_tiger'),
    comment='龙虎榜表'
    )
    op.create_index('ix_dragon_tiger_date', 'dragon_tiger', ['trade_date'], unique=False)
    op.create_index(op.f('ix_dragon_tiger_trade_date'), 'dragon_tiger', ['trade_date'], unique=False)
    op.create_index(op.f('ix_dragon_tiger_ts_code'), 'dragon_tiger', ['ts_code'], unique=False)
    op.create_table('money_flow',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('trade_date', sa.String(length=8), nullable=False, comment='交易日期'),
    sa.Column('flow_type', sa.String(length=20), nullable=True, comment='类型 (main/north/south)'),
    sa.Column('buy_elg_amount', sa.Numeric(precision=18, scale=2), nullable=True, comment='超大单买入 (万元)'),
    sa.Column('sell_elg_amount', sa.Numeric(precision=18, scale=2), nullable=True, comment='超大单卖出 (万元)'),
    sa.Column('buy_lg_amount', sa.Numeric(precision=18, scale=2), nullable=True, comment='大单买入 (万元)'),
    sa.Column('sell_lg_amount', sa.Numeric(precision=18, scale=2), nullable=True, comment='大单卖出 (万元)'),
    sa.Column('net_mf_amount', sa.Numeric(precision=18, scale=2), nullable=True, comment='主力净流入 (万元)'),
    sa.Column('net_mf_rate', sa.Numeric(precision=8, scale=4), nullable=True, comment='主力净流入占比 (%)'),
    sa.Column('north_amount', sa.Numeric(precision=18, scale=2), nullable=True, comment='北向买入金额 (万元)'),
    sa.Column('north_net', sa.Numeric(precision=18, scale=2), nullable=True, comment='北向净买入 (万元)'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('ts_code', sa.String(length=12), nullable=False, comment='股票代码 (000001.SZ)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ts_code', 'trade_date', 'flow_type', name='uq_money_flow'),
    comment='资金流向表'
    )
    op.create_index('ix_money_flow_date_type', 'money_flow', ['trade_date', 'flow_type'], unique=False)
    op.create_index(op.f('ix_money_flow_flow_type'), 'money_flow', ['flow_type'], unique=False)
    op.create_index(op.f('ix_money_flow_trade_date'), 'money_flow', ['trade_date'], unique=False)
    op.create_index(op.f('ix_money_flow_ts_code'), 'money_flow', ['ts_code'], unique=False)
    op.create_table('news',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('cleaned_data', sa.Text(), nullable=True),
    sa.Column('hotspots', sa.Text(), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_received_at', 'news', [sa.literal_column('received_at DESC')], unique=False)
    op.create_table('news_flash',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False, comment='标题'),
    sa.Column('content', sa.Text(), nullable=True, comment='正文内容'),
    sa.Column('summary', sa.Text(), nullable=True, comment='AI 摘要'),
    sa.Column('source', sa.String(length=100), nullable=True, comment='来源'),
    sa.Column('url', sa.String(length=500), nullable=True, comment='原文链接'),
    sa.Column('publish_time', sa.DateTime(), nullable=True, comment='发布时间'),
    sa.Column('ts_codes', sa.JSON(), nullable=True, comment='相关股票代码列表'),
    sa.Column('industries', sa.JSON(), nullable=True, comment='相关行业列表'),
    sa.Column('embedding', sa.JSON(), nullable=True, comment='语义向量 (1536维)'),
    sa.Column('sentiment_score', sa.Numeric(precision=4, scale=3), nullable=True, comment='情绪分数 (-1.000 ~ 1.000)'),
    sa.Column('sentiment_label', sa.String(length=20), nullable=True, comment='情绪标签 (positive/negative/neutral)'),
    sa.Column('importance', sa.Integer(), nullable=True, comment='重要性 (0-10)'),
    sa.Column('tags', sa.JSON(), nullable=True, comment='标签列表'),
    sa.Column('category', sa.String(length=50), nullable=True, comment='分类'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='新闻快讯表 (含向量)'
    )
    op.create_index('ix_news_category', 'news_flash', ['category'], unique=False)
    op.create_index(op.f('ix_news_flash_category'), 'news_flash', ['category'], unique=False)
    op.create_index(op.f('ix_news_flash_publish_time'), 'news_flash', ['publish_time'], unique=False)
    op.create_index('ix_news_publish_time', 'news_flash', ['publish_time'], unique=False)
    op.create_table('research_report',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ts_code', sa.String(length=12), nullable=True, comment='股票代码'),
    sa.Column('stock_name', sa.String(length=50), nullable=True, comment='股票名称'),
    sa.Column('title', sa.String(length=500), nullable=False, comment='报告标题'),
    sa.Column('institution', sa.String(length=100), nullable=True, comment='研究机构'),
    sa.Column('analyst', sa.String(length=100), nullable=True, comment='分析师'),
    sa.Column('rating', sa.String(length=20), nullable=True, comment='评级 (买入/增持/中性/减持/卖出)'),
    sa.Column('rating_change', sa.String(length=20), nullable=True, comment='评级变动 (上调/维持/下调)'),
    sa.Column('target_price', sa.Numeric(precision=12, scale=2), nullable=True, comment='目标价'),
    sa.Column('target_price_change', sa.Numeric(precision=8, scale=4), nullable=True, comment='目标价变动幅度'),
    sa.Column('content', sa.Text(), nullable=True, comment='报告正文'),
    sa.Column('summary', sa.Text(), nullable=True, comment='AI 摘要'),
    sa.Column('key_points', sa.JSON(), nullable=True, comment='核心观点列表'),
    sa.Column('embedding', sa.JSON(), nullable=True, comment='语义向量'),
    sa.Column('sentiment_score', sa.Numeric(precision=4, scale=3), nullable=True, comment='情绪分数'),
    sa.Column('publish_date', sa.String(length=8), nullable=True, comment='发布日期'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='研究报告表 (含向量)'
    )
    op.create_index('ix_report_code_date', 'research_report', ['ts_code', 'publish_date'], unique=False)
    op.create_index('ix_report_institution', 'research_report', ['institution'], unique=False)
    op.create_index(op.f('ix_research_report_institution'), 'research_report', ['institution'], unique=False)
    op.create_index(op.f('ix_research_report_publish_date'), 'research_report', ['publish_date'], unique=False)
    op.create_index(op.f('ix_research_report_rating'), 'research_report', ['rating'], unique=False)
    op.create_index(op.f('ix_research_report_ts_code'), 'research_report', ['ts_code'], unique=False)
    op.create_table('rss_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('link', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('published', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('link')
    )
    op.create_index('idx_rss_fetched', 'rss_items', [sa.literal_column('fetched_at DESC')], unique=False)
    op.create_table('stock_index',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ts_code', sa.String(length=12), nullable=False, comment='指数代码'),
    sa.Column('trade_date', sa.String(length=8), nullable=False, comment='交易日期'),
    sa.Column('open', sa.Numeric(precision=12, scale=2), nullable=True, comment='开盘'),
    sa.Column('high', sa.Numeric(precision=12, scale=2), nullable=True, comment='最高'),
    sa.Column('low', sa.Numeric(precision=12, scale=2), nullable=True, comment='最低'),
    sa.Column('close', sa.Numeric(precision=12, scale=2), nullable=True, comment='收盘'),
    sa.Column('pre_close', sa.Numeric(precision=12, scale=2), nullable=True, comment='昨收'),
    sa.Column('change', sa.Numeric(precision=12, scale=2), nullable=True, comment='涨跌额'),
    sa.Column('pct_chg', sa.Numeric(precision=8, scale=4), nullable=True, comment='涨跌幅 (%)'),
    sa.Column('vol', sa.BigInteger(), nullable=True, comment='成交量 (手)'),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True, comment='成交额 (千元)'),
    sa.Column('up_count', sa.Integer(), nullable=True, comment='上涨家数'),
    sa.Column('down_count', sa.Integer(), nullable=True, comment='下跌家数'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ts_code', 'trade_date', name='uq_stock_index'),
    comment='指数日线行情表'
    )
    op.create_index('ix_stock_index_code_date', 'stock_index', ['ts_code', 'trade_date'], unique=False)
    op.create_index(op.f('ix_stock_index_trade_date'), 'stock_index', ['trade_date'], unique=False)
    op.create_index(op.f('ix_stock_index_ts_code'), 'stock_index', ['ts_code'], unique=False)
    op.create_table('trade_cal',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exchange', sa.String(length=10), nullable=False, comment='交易所'),
    sa.Column('cal_date', sa.String(length=8), nullable=False, comment='日期'),
    sa.Column('is_open', sa.Boolean(), nullable=True, comment='是否交易日'),
    sa.Column('pretrade_date', sa.String(length=8), nullable=True, comment='上一个交易日'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exchange', 'cal_date', name='uq_trade_cal'),
    comment='交易日历表'
    )
    op.create_index('ix_trade_cal_date', 'trade_cal', ['cal_date'], unique=False)
    op.create_table('ts_cashflow',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ann_date', sa.String(length=8), nullable=False, comment='公告日期'),
    sa.Column('end_date', sa.String(length=8), nullable=False, comment='报告期'),
    sa.Column('n_cashflow_act', sa.Numeric(precision=18, scale=2), nullable=True, comment='经营活动产生的现金流量净额'),
    sa.Column('n_cashflow_inv_act', sa.Numeric(precision=18, scale=2), nullable=True, comment='投资活动产生的现金流量净额'),
    sa.Column('c_paid_for_fixed_assets', sa.Numeric(precision=18, scale=2), nullable=True, comment='购建固定资产等支付的现金 (Capex)'),
    sa.Column('n_cash_flows_fnc_act', sa.Numeric(precision=18, scale=2), nullable=True, comment='筹资活动产生的现金流量净额'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('ts_code', sa.String(length=12), nullable=False, comment='股票代码 (000001.SZ)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ts_code', 'ann_date', 'end_date', name='uq_ts_cashflow'),
    comment='现金流量表'
    )
    op.create_index(op.f('ix_ts_cashflow_ann_date'), 'ts_cashflow', ['ann_date'], unique=False)
    op.create_index('ix_ts_cashflow_code_date', 'ts_cashflow', ['ts_code', 'end_date'], unique=False)
    op.create_index(op.f('ix_ts_cashflow_end_date'), 'ts_cashflow', ['end_date'], unique=False)
    op.create_index(op.f('ix_ts_cashflow_ts_code'), 'ts_cashflow', ['ts_code'], unique=False)
    op.create_table('ts_cyq_perf',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trade_date', sa.String(length=8), nullable=False, comment='交易日期'),
    sa.Column('cost_5pct', sa.Numeric(precision=12, scale=2), nullable=True, comment='5分位成本'),
    sa.Column('cost_15pct', sa.Numeric(precision=12, scale=2), nullable=True, comment='15分位成本'),
    sa.Column('cost_50pct', sa.Numeric(precision=12, scale=2), nullable=True, comment='50分位成本'),
    sa.Column('cost_85pct', sa.Numeric(precision=12, scale=2), nullable=True, comment='85分位成本'),
    sa.Column('cost_95pct', sa.Numeric(precision=12, scale=2), nullable=True, comment='95分位成本'),
    sa.Column('weight_avg', sa.Numeric(precision=12, scale=2), nullable=True, comment='加权平均成本'),
    sa.Column('winner_rate', sa.Numeric(precision=8, scale=4), nullable=True, comment='获利盘比例'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('ts_code', sa.String(length=12), nullable=False, comment='股票代码 (000001.SZ)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ts_code', 'trade_date', name='uq_ts_cyq_perf'),
    comment='筹码分布表'
    )
    op.create_index('ix_ts_cyq_perf_date', 'ts_cyq_perf', ['trade_date'], unique=False)
    op.create_index(op.f('ix_ts_cyq_perf_trade_date'), 'ts_cyq_perf', ['trade_date'], unique=False)
    op.create_index(op.f('ix_ts_cyq_perf_ts_code'), 'ts_cyq_perf', ['ts_code'], unique=False)
    op.create_table('ts_daily',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('trade_date', sa.String(length=8), nullable=False, comment='交易日期'),
    sa.Column('open', sa.Numeric(precision=12, scale=2), nullable=True, comment='开盘价'),
    sa.Column('high', sa.Numeric(precision=12, scale=2), nullable=True, comment='最高价'),
    sa.Column('low', sa.Numeric(precision=12, scale=2), nullable=True, comment='最低价'),
    sa.Column('close', sa.Numeric(precision=12, scale=2), nullable=True, comment='收盘价'),
    sa.Column('pre_close', sa.Numeric(precision=12, scale=2), nullable=True, comment='昨收价'),
    sa.Column('change', sa.Numeric(precision=12, scale=2), nullable=True, comment='涨跌额'),
    sa.Column('pct_chg', sa.Numeric(precision=8, scale=4), nullable=True, comment='涨跌幅 (%)'),
    sa.Column('vol', sa.BigInteger(), nullable=True, comment='成交量 (手)'),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True, comment='成交额 (千元)'),
    sa.Column('adj_factor', sa.Numeric(precision=10, scale=6), nullable=True, comment='复权因子'),
    sa.Column('qfq_close', sa.Numeric(precision=12, scale=2), nullable=True, comment='前复权收盘价 (预计算)'),
    sa.Column('hfq_close', sa.Numeric(precision=12, scale=2), nullable=True, comment='后复权收盘价 (预计算)'),
    sa.Column('turnover_rate', sa.Numeric(precision=8, scale=4), nullable=True, comment='换手率 (%)'),
    sa.Column('volume_ratio', sa.Numeric(precision=6, scale=2), nullable=True, comment='量比'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('ts_code', sa.String(length=12), nullable=False, comment='股票代码 (000001.SZ)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ts_code', 'trade_date', name='uq_stock_daily'),
    comment='股票日线行情表'
    )
    op.create_index('ix_stock_daily_code_date', 'ts_daily', ['ts_code', 'trade_date'], unique=False)
    op.create_index('ix_stock_daily_date', 'ts_daily', ['trade_date'], unique=False)
    op.create_index(op.f('ix_ts_daily_trade_date'), 'ts_daily', ['trade_date'], unique=False)
    op.create_index(op.f('ix_ts_daily_ts_code'), 'ts_daily', ['ts_code'], unique=False)
    op.create_table('ts_daily_basic',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trade_date', sa.String(length=8), nullable=False, comment='交易日期'),
    sa.Column('turnover_rate', sa.Numeric(precision=8, scale=4), nullable=True, comment='换手率 (%)'),
    sa.Column('turnover_rate_f', sa.Numeric(precision=8, scale=4), nullable=True, comment='换手率(自由流通股) (%)'),
    sa.Column('volume_ratio', sa.Numeric(precision=6, scale=2), nullable=True, comment='量比'),
    sa.Column('pe', sa.Numeric(precision=10, scale=4), nullable=True, comment='PE'),
    sa.Column('pe_ttm', sa.Numeric(precision=10, scale=4), nullable=True, comment='PE_TTM'),
    sa.Column('pb', sa.Numeric(precision=10, scale=4), nullable=True, comment='PB'),
    sa.Column('ps', sa.Numeric(precision=10, scale=4), nullable=True, comment='PS'),
    sa.Column('ps_ttm', sa.Numeric(precision=10, scale=4), nullable=True, comment='PS_TTM'),
    sa.Column('dv_ratio', sa.Numeric(precision=8, scale=4), nullable=True, comment='股息率 (%)'),
    sa.Column('dv_ttm', sa.Numeric(precision=8, scale=4), nullable=True, comment='股息率_TTM (%)'),
    sa.Column('total_share', sa.Numeric(precision=18, scale=2), nullable=True, comment='总股本 (万股)'),
    sa.Column('float_share', sa.Numeric(precision=18, scale=2), nullable=True, comment='流通股本 (万股)'),
    sa.Column('free_share', sa.Numeric(precision=18, scale=2), nullable=True, comment='自由流通股本 (万股)'),
    sa.Column('total_mv', sa.Numeric(precision=18, scale=2), nullable=True, comment='总市值 (万元)'),
    sa.Column('circ_mv', sa.Numeric(precision=18, scale=2), nullable=True, comment='流通市值 (万元)'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('ts_code', sa.String(length=12), nullable=False, comment='股票代码 (000001.SZ)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ts_code', 'trade_date', name='uq_ts_daily_basic'),
    comment='每日指标表'
    )
    op.create_index('ix_ts_daily_basic_date', 'ts_daily_basic', ['trade_date'], unique=False)
    op.create_index(op.f('ix_ts_daily_basic_trade_date'), 'ts_daily_basic', ['trade_date'], unique=False)
    op.create_index(op.f('ix_ts_daily_basic_ts_code'), 'ts_daily_basic', ['ts_code'], unique=False)
    op.create_table('ts_hk_hold',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trade_date', sa.String(length=8), nullable=False, comment='交易日期'),
    sa.Column('vol', sa.BigInteger(), nullable=True, comment='持股数量 (股)'),
    sa.Column('ratio', sa.Numeric(precision=8, scale=4), nullable=True, comment='持股占比 (%)'),
    sa.Column('exchange', sa.String(length=10), nullable=True, comment='类型 (SH/SZ/HK)'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('ts_code', sa.String(length=12), nullable=False, comment='股票代码 (000001.SZ)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ts_code', 'trade_date', name='uq_ts_hk_hold'),
    comment='沪深港股通持股表'
    )
    op.create_index('ix_ts_hk_hold_date', 'ts_hk_hold', ['trade_date'], unique=False)
    op.create_index(op.f('ix_ts_hk_hold_exchange'), 'ts_hk_hold', ['exchange'], unique=False)
    op.create_index(op.f('ix_ts_hk_hold_trade_date'), 'ts_hk_hold', ['trade_date'], unique=False)
    op.create_index(op.f('ix_ts_hk_hold_ts_code'), 'ts_hk_hold', ['ts_code'], unique=False)
    op.create_table('ts_stock_basic',
    sa.Column('ts_code', sa.String(length=12), nullable=False, comment='股票代码 (000001.SZ)'),
    sa.Column('symbol', sa.String(length=6), nullable=False, comment='6位代码'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='股票名称'),
    sa.Column('area', sa.String(length=20), nullable=True, comment='地区'),
    sa.Column('industry', sa.String(length=50), nullable=True, comment='所属行业'),
    sa.Column('market', sa.String(length=20), nullable=True, comment='市场 (主板/创业板/科创板/北交所)'),
    sa.Column('exchange', sa.String(length=10), nullable=True, comment='交易所 (SSE/SZSE/BSE)'),
    sa.Column('list_status', sa.String(length=1), nullable=True, comment='上市状态 (L/D/P)'),
    sa.Column('list_date', sa.String(length=8), nullable=True, comment='上市日期 (YYYYMMDD)'),
    sa.Column('delist_date', sa.String(length=8), nullable=True, comment='退市日期'),
    sa.Column('is_hs', sa.String(length=1), nullable=True, comment='沪深港通 (N/H/S)'),
    sa.Column('fullname', sa.String(length=100), nullable=True, comment='公司全称'),
    sa.Column('cn_spell', sa.String(length=50), nullable=True, comment='拼音首字母'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('ts_code'),
    comment='股票基础信息表'
    )
    op.create_index('ix_stock_basic_market_industry', 'ts_stock_basic', ['market', 'industry'], unique=False)
    op.create_index(op.f('ix_ts_stock_basic_industry'), 'ts_stock_basic', ['industry'], unique=False)
    op.create_index(op.f('ix_ts_stock_basic_market'), 'ts_stock_basic', ['market'], unique=False)
    op.create_index(op.f('ix_ts_stock_basic_symbol'), 'ts_stock_basic', ['symbol'], unique=False)
    op.create_table('ts_top10_holders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ann_date', sa.String(length=8), nullable=True, comment='公告日期'),
    sa.Column('end_date', sa.String(length=8), nullable=True, comment='报告期'),
    sa.Column('holder_name', sa.String(length=100), nullable=True, comment='股东名称'),
    sa.Column('hold_amount', sa.BigInteger(), nullable=True, comment='持有数量 (股)'),
    sa.Column('hold_ratio', sa.Numeric(precision=8, scale=4), nullable=True, comment='持有比例 (%)'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('ts_code', sa.String(length=12), nullable=False, comment='股票代码 (000001.SZ)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ts_code', 'ann_date', 'holder_name', name='uq_ts_top10_holders'),
    comment='前十大股东表'
    )
    op.create_index(op.f('ix_ts_top10_holders_ann_date'), 'ts_top10_holders', ['ann_date'], unique=False)
    op.create_index(op.f('ix_ts_top10_holders_end_date'), 'ts_top10_holders', ['end_date'], unique=False)
    op.create_index(op.f('ix_ts_top10_holders_holder_name'), 'ts_top10_holders', ['holder_name'], unique=False)
    op.create_index('ix_ts_top10_holders_name', 'ts_top10_holders', ['holder_name'], unique=False)
    op.create_index(op.f('ix_ts_top10_holders_ts_code'), 'ts_top10_holders', ['ts_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ts_top10_holders_ts_code'), table_name='ts_top10_holders')
    op.drop_index('ix_ts_top10_holders_name', table_name='ts_top10_holders')
    op.drop_index(op.f('ix_ts_top10_holders_holder_name'), table_name='ts_top10_holders')
    op.drop_index(op.f('ix_ts_top10_holders_end_date'), table_name='ts_top10_holders')
    op.drop_index(op.f('ix_ts_top10_holders_ann_date'), table_name='ts_top10_holders')
    op.drop_table('ts_top10_holders')
    op.drop_index(op.f('ix_ts_stock_basic_symbol'), table_name='ts_stock_basic')
    op.drop_index(op.f('ix_ts_stock_basic_market'), table_name='ts_stock_basic')
    op.drop_index(op.f('ix_ts_stock_basic_industry'), table_name='ts_stock_basic')
    op.drop_index('ix_stock_basic_market_industry', table_name='ts_stock_basic')
    op.drop_table('ts_stock_basic')
    op.drop_index(op.f('ix_ts_hk_hold_ts_code'), table_name='ts_hk_hold')
    op.drop_index(op.f('ix_ts_hk_hold_trade_date'), table_name='ts_hk_hold')
    op.drop_index(op.f('ix_ts_hk_hold_exchange'), table_name='ts_hk_hold')
    op.drop_index('ix_ts_hk_hold_date', table_name='ts_hk_hold')
    op.drop_table('ts_hk_hold')
    op.drop_index(op.f('ix_ts_daily_basic_ts_code'), table_name='ts_daily_basic')
    op.drop_index(op.f('ix_ts_daily_basic_trade_date'), table_name='ts_daily_basic')
    op.drop_index('ix_ts_daily_basic_date', table_name='ts_daily_basic')
    op.drop_table('ts_daily_basic')
    op.drop_index(op.f('ix_ts_daily_ts_code'), table_name='ts_daily')
    op.drop_index(op.f('ix_ts_daily_trade_date'), table_name='ts_daily')
    op.drop_index('ix_stock_daily_date', table_name='ts_daily')
    op.drop_index('ix_stock_daily_code_date', table_name='ts_daily')
    op.drop_table('ts_daily')
    op.drop_index(op.f('ix_ts_cyq_perf_ts_code'), table_name='ts_cyq_perf')
    op.drop_index(op.f('ix_ts_cyq_perf_trade_date'), table_name='ts_cyq_perf')
    op.drop_index('ix_ts_cyq_perf_date', table_name='ts_cyq_perf')
    op.drop_table('ts_cyq_perf')
    op.drop_index(op.f('ix_ts_cashflow_ts_code'), table_name='ts_cashflow')
    op.drop_index(op.f('ix_ts_cashflow_end_date'), table_name='ts_cashflow')
    op.drop_index('ix_ts_cashflow_code_date', table_name='ts_cashflow')
    op.drop_index(op.f('ix_ts_cashflow_ann_date'), table_name='ts_cashflow')
    op.drop_table('ts_cashflow')
    op.drop_index('ix_trade_cal_date', table_name='trade_cal')
    op.drop_table('trade_cal')
    op.drop_index(op.f('ix_stock_index_ts_code'), table_name='stock_index')
    op.drop_index(op.f('ix_stock_index_trade_date'), table_name='stock_index')
    op.drop_index('ix_stock_index_code_date', table_name='stock_index')
    op.drop_table('stock_index')
    op.drop_index('idx_rss_fetched', table_name='rss_items')
    op.drop_table('rss_items')
    op.drop_index(op.f('ix_research_report_ts_code'), table_name='research_report')
    op.drop_index(op.f('ix_research_report_rating'), table_name='research_report')
    op.drop_index(op.f('ix_research_report_publish_date'), table_name='research_report')
    op.drop_index(op.f('ix_research_report_institution'), table_name='research_report')
    op.drop_index('ix_report_institution', table_name='research_report')
    op.drop_index('ix_report_code_date', table_name='research_report')
    op.drop_table('research_report')
    op.drop_index('ix_news_publish_time', table_name='news_flash')
    op.drop_index(op.f('ix_news_flash_publish_time'), table_name='news_flash')
    op.drop_index(op.f('ix_news_flash_category'), table_name='news_flash')
    op.drop_index('ix_news_category', table_name='news_flash')
    op.drop_table('news_flash')
    op.drop_index('idx_received_at', table_name='news')
    op.drop_table('news')
    op.drop_index(op.f('ix_money_flow_ts_code'), table_name='money_flow')
    op.drop_index(op.f('ix_money_flow_trade_date'), table_name='money_flow')
    op.drop_index(op.f('ix_money_flow_flow_type'), table_name='money_flow')
    op.drop_index('ix_money_flow_date_type', table_name='money_flow')
    op.drop_table('money_flow')
    op.drop_index(op.f('ix_dragon_tiger_ts_code'), table_name='dragon_tiger')
    op.drop_index(op.f('ix_dragon_tiger_trade_date'), table_name='dragon_tiger')
    op.drop_index('ix_dragon_tiger_date', table_name='dragon_tiger')
    op.drop_table('dragon_tiger')
    op.drop_index('ix_block_daily_type_date', table_name='block_daily')
    op.drop_index(op.f('ix_block_daily_trade_date'), table_name='block_daily')
    op.drop_index(op.f('ix_block_daily_block_type'), table_name='block_daily')
    op.drop_index(op.f('ix_block_daily_block_code'), table_name='block_daily')
    op.drop_table('block_daily')
    op.drop_index('idx_analysis_date', table_name='analysis_results')
    op.drop_table('analysis_results')
    # ### end Alembic commands ###
